language: node_js

env:
  - DATABASE_URL=postgresql://coder:pg123@localhost:5432/my_registration'
  
node_js:
  - "8.9.4"

before_script:
  - psql -c 'create database  greeting_app_database;' -U postgres
  - psql -U postgres -d greeting_app_database -a -f table.sql

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2