language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/my_registration'
  
node_js:
  - "8.9.4"

before_script:
  - psql -c 'create database  my_registration;' -U postgres
  - psql -U postgres -d my_registration -a -f table.sql

  
addons:
    apt:
    packages:
    - postgresql-server-dev-9.2
